//! The global names this analysis attributes to the TypeScript standard
//! library.
//!
//! Port of `packages/jskit/src/types/well-known.ts`. The table is part of
//! the analysis contract even though it never appears in a buffer: adding a
//! name changes the origin the walk assigns, so the two implementations must
//! carry the same list.

/// The known standard-library global type names.
const WELL_KNOWN_LIB_TYPES: [&str; 107] = [
    "Object",
    "Function",
    "Boolean",
    "Symbol",
    "String",
    "Number",
    "BigInt",
    "Math",
    "Date",
    "RegExp",
    "JSON",
    "Error",
    "AggregateError",
    "EvalError",
    "RangeError",
    "ReferenceError",
    "SyntaxError",
    "TypeError",
    "URIError",
    "Array",
    "ReadonlyArray",
    "Map",
    "ReadonlyMap",
    "Set",
    "ReadonlySet",
    "WeakMap",
    "WeakSet",
    "WeakRef",
    "ArrayBuffer",
    "SharedArrayBuffer",
    "DataView",
    "Int8Array",
    "Uint8Array",
    "Uint8ClampedArray",
    "Int16Array",
    "Uint16Array",
    "Int32Array",
    "Uint32Array",
    "Float32Array",
    "Float64Array",
    "BigInt64Array",
    "BigUint64Array",
    "Promise",
    "PromiseLike",
    "PromiseConstructor",
    "Awaited",
    "Iterable",
    "Iterator",
    "IterableIterator",
    "AsyncIterable",
    "AsyncIterator",
    "AsyncIterableIterator",
    "Generator",
    "AsyncGenerator",
    "GeneratorFunction",
    "AsyncGeneratorFunction",
    "Proxy",
    "Reflect",
    "Atomics",
    "FinalizationRegistry",
    "Intl",
    "Partial",
    "Required",
    "Readonly",
    "Record",
    "Pick",
    "Omit",
    "Exclude",
    "Extract",
    "NonNullable",
    "Parameters",
    "ConstructorParameters",
    "ReturnType",
    "InstanceType",
    "ThisParameterType",
    "OmitThisParameter",
    "ThisType",
    "Uppercase",
    "Lowercase",
    "Capitalize",
    "Uncapitalize",
    "NoInfer",
    "URL",
    "URLSearchParams",
    "TextEncoder",
    "TextDecoder",
    "Window",
    "Document",
    "Element",
    "HTMLElement",
    "Node",
    "Event",
    "EventTarget",
    "AbortController",
    "AbortSignal",
    "Blob",
    "File",
    "FormData",
    "Headers",
    "Request",
    "Response",
    "ReadableStream",
    "WritableStream",
    "TransformStream",
    "MessagePort",
    "Worker",
    "Console",
];

/// Reports whether an unresolved global name, given as UTF-16 code units, is
/// one the TypeScript standard library declares.
pub fn is_well_known_lib_type(name: &[u16]) -> bool {
    WELL_KNOWN_LIB_TYPES.iter().any(|candidate| {
        candidate.len() == name.len()
            && candidate
                .bytes()
                .zip(name.iter())
                .all(|(byte, &unit)| u16::from(byte) == unit)
    })
}
