/**
 * @fileoverview Which properties of each node kind hold its children.
 *
 * ESLint walks a tree by looking each node type up in a table like this one,
 * and falls back to enumerating every own property of a node whose type it
 * does not know. That fallback is why a missing entry is not a loud failure:
 * traversal keeps working, but the walk visits properties that are not
 * children, in an order nobody chose.
 *
 * The entries are what `@typescript-eslint/visitor-keys` states, key for key
 * and in the same order, because the tree they describe is the one this
 * package produces. `tests/parse/visitor-keys.test.ts` compares the two, so a
 * node kind added without an entry here fails there.
 *
 * The JavaScript entries are a superset of `eslint-visitor-keys`: they carry
 * the TypeScript-only properties as well, which a `dialect: "js"` tree simply
 * does not have. A key naming a property that is absent costs one lookup and
 * nothing else.
 */

/**
 * The child-bearing properties of every node kind this package produces, in
 * the order a walk should visit them.
 */
export const VISITOR_KEYS: Readonly<Record<string, readonly string[]>> = {
	Program: ["body"],
	Identifier: ["decorators", "typeAnnotation"],
	PrivateIdentifier: [],
	Literal: [],
	TemplateLiteral: ["quasis", "expressions"],
	TemplateElement: [],
	TaggedTemplateExpression: ["tag", "typeArguments", "quasi"],
	ExpressionStatement: ["expression"],
	BlockStatement: ["body"],
	StaticBlock: ["body"],
	EmptyStatement: [],
	DebuggerStatement: [],
	WithStatement: ["object", "body"],
	ReturnStatement: ["argument"],
	LabeledStatement: ["label", "body"],
	BreakStatement: ["label"],
	ContinueStatement: ["label"],
	IfStatement: ["test", "consequent", "alternate"],
	SwitchStatement: ["discriminant", "cases"],
	SwitchCase: ["test", "consequent"],
	ThrowStatement: ["argument"],
	TryStatement: ["block", "handler", "finalizer"],
	CatchClause: ["param", "body"],
	WhileStatement: ["test", "body"],
	DoWhileStatement: ["body", "test"],
	ForStatement: ["init", "test", "update", "body"],
	ForInStatement: ["left", "right", "body"],
	ForOfStatement: ["left", "right", "body"],
	VariableDeclaration: ["declarations"],
	VariableDeclarator: ["id", "init"],
	FunctionDeclaration: [
		"id",
		"typeParameters",
		"params",
		"returnType",
		"body",
	],
	FunctionExpression: [
		"id",
		"typeParameters",
		"params",
		"returnType",
		"body",
	],
	ArrowFunctionExpression: ["typeParameters", "params", "returnType", "body"],
	ClassDeclaration: [
		"decorators",
		"id",
		"typeParameters",
		"superClass",
		"superTypeArguments",
		"implements",
		"body",
	],
	ClassExpression: [
		"decorators",
		"id",
		"typeParameters",
		"superClass",
		"superTypeArguments",
		"implements",
		"body",
	],
	ClassBody: ["body"],
	MethodDefinition: ["decorators", "key", "value"],
	PropertyDefinition: ["decorators", "key", "typeAnnotation", "value"],
	AccessorProperty: ["decorators", "key", "typeAnnotation", "value"],
	ThisExpression: [],
	ArrayExpression: ["elements"],
	ObjectExpression: ["properties"],
	Property: ["key", "value"],
	SequenceExpression: ["expressions"],
	UnaryExpression: ["argument"],
	UpdateExpression: ["argument"],
	BinaryExpression: ["left", "right"],
	AssignmentExpression: ["left", "right"],
	LogicalExpression: ["left", "right"],
	ConditionalExpression: ["test", "consequent", "alternate"],
	CallExpression: ["callee", "typeArguments", "arguments"],
	NewExpression: ["callee", "typeArguments", "arguments"],
	MemberExpression: ["object", "property"],
	YieldExpression: ["argument"],
	AwaitExpression: ["argument"],
	ImportExpression: ["source", "options"],
	ChainExpression: ["expression"],
	MetaProperty: ["meta", "property"],
	Super: [],
	SpreadElement: ["argument"],
	RestElement: ["decorators", "argument", "typeAnnotation"],
	AssignmentPattern: ["decorators", "left", "right", "typeAnnotation"],
	ArrayPattern: ["decorators", "elements", "typeAnnotation"],
	ObjectPattern: ["decorators", "properties", "typeAnnotation"],
	ImportDeclaration: ["specifiers", "source", "attributes"],
	ImportSpecifier: ["imported", "local"],
	ImportDefaultSpecifier: ["local"],
	ImportNamespaceSpecifier: ["local"],
	ImportAttribute: ["key", "value"],
	ExportNamedDeclaration: [
		"declaration",
		"specifiers",
		"source",
		"attributes",
	],
	ExportSpecifier: ["local", "exported"],
	ExportDefaultDeclaration: ["declaration"],
	ExportAllDeclaration: ["exported", "source", "attributes"],
	Decorator: ["expression"],
	JSXElement: ["openingElement", "children", "closingElement"],
	JSXFragment: ["openingFragment", "children", "closingFragment"],
	JSXOpeningElement: ["name", "typeArguments", "attributes"],
	JSXClosingElement: ["name"],
	JSXOpeningFragment: [],
	JSXClosingFragment: [],
	JSXAttribute: ["name", "value"],
	JSXSpreadAttribute: ["argument"],
	JSXIdentifier: [],
	JSXNamespacedName: ["namespace", "name"],
	JSXMemberExpression: ["object", "property"],
	JSXExpressionContainer: ["expression"],
	JSXEmptyExpression: [],
	JSXSpreadChild: ["expression"],
	JSXText: [],
	TSTypeAnnotation: ["typeAnnotation"],
	TSTypeParameterDeclaration: ["params"],
	TSTypeParameter: ["name", "constraint", "default"],
	TSTypeParameterInstantiation: ["params"],
	TSAnyKeyword: [],
	TSBigIntKeyword: [],
	TSBooleanKeyword: [],
	TSNeverKeyword: [],
	TSNullKeyword: [],
	TSNumberKeyword: [],
	TSObjectKeyword: [],
	TSStringKeyword: [],
	TSSymbolKeyword: [],
	TSUndefinedKeyword: [],
	TSUnknownKeyword: [],
	TSVoidKeyword: [],
	TSIntrinsicKeyword: [],
	TSThisType: [],
	TSArrayType: ["elementType"],
	TSTupleType: ["elementTypes"],
	TSNamedTupleMember: ["label", "elementType"],
	TSRestType: ["typeAnnotation"],
	TSOptionalType: ["typeAnnotation"],
	TSUnionType: ["types"],
	TSIntersectionType: ["types"],
	TSConditionalType: ["checkType", "extendsType", "trueType", "falseType"],
	TSInferType: ["typeParameter"],
	TSTypeOperator: ["typeAnnotation"],
	TSIndexedAccessType: ["objectType", "indexType"],
	TSMappedType: ["key", "constraint", "nameType", "typeAnnotation"],
	TSLiteralType: ["literal"],
	TSTemplateLiteralType: ["quasis", "types"],
	TSTypeReference: ["typeName", "typeArguments"],
	TSQualifiedName: ["left", "right"],
	TSTypeQuery: ["exprName", "typeArguments"],
	TSTypePredicate: ["parameterName", "typeAnnotation"],
	TSFunctionType: ["typeParameters", "params", "returnType"],
	TSConstructorType: ["typeParameters", "params", "returnType"],
	TSTypeLiteral: ["members"],
	TSImportType: ["source", "options", "qualifier", "typeArguments"],
	TSPropertySignature: ["key", "typeAnnotation"],
	TSMethodSignature: ["key", "typeParameters", "params", "returnType"],
	TSIndexSignature: ["parameters", "typeAnnotation"],
	TSCallSignatureDeclaration: ["typeParameters", "params", "returnType"],
	TSConstructSignatureDeclaration: ["typeParameters", "params", "returnType"],
	TSInterfaceDeclaration: ["id", "typeParameters", "extends", "body"],
	TSInterfaceBody: ["body"],
	TSInterfaceHeritage: ["expression", "typeArguments"],
	TSClassImplements: ["expression", "typeArguments"],
	TSTypeAliasDeclaration: ["id", "typeParameters", "typeAnnotation"],
	TSEnumDeclaration: ["id", "body"],
	TSEnumBody: ["members"],
	TSEnumMember: ["id", "initializer"],
	TSModuleDeclaration: ["id", "body"],
	TSModuleBlock: ["body"],
	TSDeclareFunction: ["id", "typeParameters", "params", "returnType", "body"],
	TSAbstractMethodDefinition: ["key", "value"],
	TSAbstractPropertyDefinition: ["decorators", "key", "typeAnnotation"],
	TSAbstractAccessorProperty: ["decorators", "key", "typeAnnotation"],
	TSParameterProperty: ["decorators", "parameter"],
	TSEmptyBodyFunctionExpression: [
		"id",
		"typeParameters",
		"params",
		"returnType",
	],
	TSAsExpression: ["expression", "typeAnnotation"],
	TSSatisfiesExpression: ["expression", "typeAnnotation"],
	TSNonNullExpression: ["expression"],
	TSTypeAssertion: ["typeAnnotation", "expression"],
	TSInstantiationExpression: ["expression", "typeArguments"],
	TSExportAssignment: ["expression"],
	TSImportEqualsDeclaration: ["id", "moduleReference"],
	TSExternalModuleReference: ["expression"],
	TSAbstractKeyword: [],
	TSDeclareKeyword: [],
	TSExportKeyword: [],
	TSNamespaceExportDeclaration: ["id"],
};
